// <auto-generated />
using Hostility_Skirmish.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hostility_Skirmish.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191120211246_FirstMigrations")]
    partial class FirstMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hostility_Skirmish.Models.GameClasses.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ability_Slot");

                    b.Property<int>("AttackPower");

                    b.Property<string>("Avatar_Slot");

                    b.Property<int>("DefensePower");

                    b.Property<int>("Health");

                    b.Property<bool>("IsAlive");

                    b.Property<string>("Item_Slot");

                    b.Property<int>("PartyId");

                    b.Property<bool>("TurnTaken");

                    b.HasKey("CharacterId");

                    b.HasIndex("PartyId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Hostility_Skirmish.Models.GameClasses.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PartyName");

                    b.Property<int>("UserId");

                    b.Property<int>("Wins");

                    b.HasKey("PartyId");

                    b.HasIndex("UserId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Hostility_Skirmish.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Challenged");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<bool>("Logged");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hostility_Skirmish.Models.GameClasses.Character", b =>
                {
                    b.HasOne("Hostility_Skirmish.Models.GameClasses.Party", "Party")
                        .WithMany("Characters")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hostility_Skirmish.Models.GameClasses.Party", b =>
                {
                    b.HasOne("Hostility_Skirmish.Models.User", "User")
                        .WithMany("Parties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
